### ISSUE TITLE
Maximum publishing rate

### ISSUE THREAD

**Issue by ghost** [Mayankm96/airsim_ros_client#5]
i used your wrapper and modified it for a small project to publish the images to ros , but i noticed that the rate of the publishing rate only goes up to a maximum of 11 even whether i increased the Rate loop_rate() in img_publisher.py and the pubImages.launch files, is it because my processor ran out of juice or something else? I noticed one of my core is running at 100% (assuming it's running on a single thread).

**Comment by Mayankm96** [comment]
What is the height and width of the images you are trying to use?

With my machine (8th Gen Intel i7, 16GB RAM, and 8GB NVidia-1070 graphics card). for 720p images, I am able to get a frame rate of 2-3 Hz which increases to 4-5 Hz with "NoDisplay" view mode on. However, the issue is at the AirSim end since it takes a lot of time to retrieve depth images through the API call. 

If you want to increase the frame rate, you can decrease the size of the images to 480p. That's the only possible solution for now.
